
# Academy data pipeline -- Data extraction from text to CSV

<h3>Extracting data from modules text and save it in a dataframe: Approach </h3>
<ol type="1">
  <li> Reading the Document </li>
    <li> Structure the Data: Parsing the data following the hierarchical structure of the doc by parsing categorically ( sections, slides, and media) keeping the text style </li>
    <li> Create DataFrame:Convert this structured data into a pandas DataFrame </li>
    
</ol>

In [1]:
# Import libraries 
from docx import Document 
import pandas as pd
import os
import re

Read the doc

In [2]:
# read the test .docx file
docx_path = 'Modules/sea-test.docx'

# load the document
document = Document(docx_path)

# extract text from the document
doc_text = []
for para in document.paragraphs:
    doc_text.append(para.text)

# print the text
print('\n'.join(doc_text))

#5.3.2 Energy Transition

*Slide* [Innovation in the Just Energy Transition]

**Photo**
img=access-1

**Text-narrow**

Energy lorem ipsum alo vil cu li li oppo energy sustainable etc Energy lorem ipsum alo vil cu li li oppo energy sustainable etc Energy lorem ipsum alo vil cu li li oppo energy sustainable


**Text-wide**
Energy lorem ipsum alo vil cu li li oppo
Energy lorem ipsum alo vil cu li li oppo energy sustainable etc
Energy lorem ipsum alo vil cu li li oppo energy sustainable etc

*Slide* [Energy Access]

**Photo-Box**

img=access-3

**Text**

Energy lorem ipsum alo vil

**Diagram**

dgm=transition-2

Here the diagram shows that renewable energy is good.


**Text-dark-6**

Energy lorem ipsum alo vil cu li li oppo energy sustainable etc
Energy lorem ipsum alo vil cu li li oppo energy sustainable etc
Energy lorem ipsum alo vil cu li li oppo energy sustainable etc


**Text-dark-4**

Energy lorem ipsum alo vil cu li li oppo energy sustainable etc Energy lorem ipsum alo vil cu li li oppo energy sustainable etc Energy lorem ipsum alo vil cu li li oppo energy sustainable


**Photo-5**

img=access-1

**Photo-5**

img=access-1


*****

### Parsing

In [23]:
def extract_text_with_styles(doc):
    """Extracts text from a DOCX document, preserving some style elements, including text size."""
    text = []
    for para in doc.paragraphs:
        para_text = ""
        for run in para.runs:
            style_prefix = ""
            style_suffix = ""
            # Basic styles
            if run.bold:
                style_prefix += "<b>"
                style_suffix = "</b>" + style_suffix
            if run.italic:
                style_prefix += "<i>"
                style_suffix = "</i>" + style_suffix
            if run.underline:
                style_prefix += "<u>"
                style_suffix = "</u>" + style_suffix
            # Text color
            if run.font.color.rgb:
                color = run.font.color.rgb  # Color is an RGBColor object
                style_prefix += f'<span style="color:#{color}">'
                style_suffix = "</span>" + style_suffix
            # Text size
            if run.font.size:  # Font size is reported in Pt
                size_pt = run.font.size.pt
                if size_pt > 12:  # Assuming default text size is 12pt, customize as needed
                    style_prefix += f'<span style="font-size:{size_pt}pt;">'
                    style_suffix = "</span>" + style_suffix

            para_text += f"{style_prefix}{run.text}{style_suffix}"

        # Heading handling
        if para.style.name.startswith('Heading'):
            level = para.style.name.split()[-1]
            text.append(f'<h{level}>{para_text}</h{level}>')
        else:
            text.append(para_text)
    return '\n'.join(text)


def parse_document(document_text):
    # Initialize variables
    data = []
    section_num, section_title, slide_title = '', '', ''
    slide_number = 0  # Slide numbering starts at 0 and increments each time a new slide is found
  

    lines = document_text.split('\n')
    for line in lines:
        # Handle section headers
        section_header_match = re.match(r'#\s*(\d+\.\d+\.\d+)\s+(.*)', line)
        if section_header_match:
            section_num = section_header_match.group(1)
            section_title = section_header_match.group(2)
            slide_number = 0  # Reset slide number for each new section
            continue  # Skip adding a row for the section header

        if '*Slide*' in line:
            # Increment slide number for each new slide
            slide_number += 1
            slide_title = re.findall(r'\[([^\]]+)\]', line)[0]
            continue  # Skip adding a row for the slide title

        # Determine type based on content
        if 'img=' in line or 'dgm=' in line:
            code_type, code = line.split('=')
            row_type = 'Photo' if 'img' in code_type else 'Diagram'
            data.append({
                'Type': row_type,
                'Code': code.strip(),
                'Section Number': section_num,
                'Section Title': section_title,
                'Slide Number': slide_number,
                'Slide Title': slide_title,
                'Text': '',
                'Column Number': '',
                'Column Width': '',
                'Theme': ''
                
            })
    
        else:
            # Add regular text content
            data.append({
                'Type': 'Text',
                'Code': '',
                'Section Number': section_num,
                'Section Title': section_title,
                'Slide Number': slide_number,
                'Slide Title': slide_title,
                'Text': line,
                'Order': order
            })
            order += 1

    return pd.DataFrame(data)

# Example of reading and processing a DOCX file
doc_path = '../03_Inputs/Modules/sea-test.docx'  # Adjust this path if necessary
doc = Document(doc_path)
document_text = extract_text_with_styles(doc)
df = parse_document(document_text)
df

,Type,Code,Section Number,Section Title,Slide Number,Slide Title,Text,Order
0,Text,,5.3.2,Energy Transition,0,,,1
1,Text,,5.3.2,Energy Transition,1,Innovation in the Just Energy Transition,,2
2,Text,,5.3.2,Energy Transition,1,Innovation in the Just Energy Transition,,3
3,Text,,5.3.2,Energy Transition,1,Innovation in the Just Energy Transition,**Photo**,4
4,Text,,5.3.2,Energy Transition,1,Innovation in the Just Energy Transition,,5
5,Photo,access-1,5.3.2,Energy Transition,1,Innovation in the Just Energy Transition,,6
6,Text,,5.3.2,Energy Transition,1,Innovation in the Just Energy Transition,,7
7,Text,,5.3.2,Energy Transition,1,Innovation in the Just Energy Transition,**Text-narrow**,8
8,Text,,5.3.2,Energy Transition,1,Innovation in the Just Energy Transition,,9
9,Text,,5.3.2,Energy Transition,1,Innovation in the Just Energy Transition,Energy lorem ipsum alo vil cu li li oppo energ...,10
10,Text,,5.3.2,Energy Transition,1,Innovation in the Just Energy Transition,,11
11,Text,,5.3.2,Energy Transition,1,Innovation in the Just Energy Transition,,12
12,Text,,5.3.2,Energy Transition,1,Innovation in the Just Energy Transition,**Text-wide**,13
13,Text,,5.3.2,Energy Transition,1,Innovation in the Just Energy Transition,<h1>Energy lorem ipsum alo vil cu li li oppo <...,14
14,Text,,5.3.2,Energy Transition,1,Innovation in the Just Energy Transition,Energy lorem <b>ipsum </b><b>alo</b><b> </b><b...,15
15,Text,,5.3.2,Energy Transition,1,Innovation in the Just Energy Transition,Energy lorem ipsum alo vil cu li li oppo energ...,16
16,Text,,5.3.2,Energy Transition,1,Innovation in the Just Energy Transition,,17
17,Text,,5.3.2,Energy Transition,2,Energy Access,,18
18,Text,,5.3.2,Energy Transition,2,Energy Access,**Photo-Box**,19
19,Text,,5.3.2,Energy Transition,2,Energy Access,,20
20,Photo,access-3,5.3.2,Energy Transition,2,Energy Access,,21
21,Text,,5.3.2,Energy Transition,2,Energy Access,,22
22,Text,,5.3.2,Energy Transition,2,Energy Access,**Text**,23
23,Text,,5.3.2,Energy Transition,2,Energy Access,,24
24,Text,,5.3.2,Energy Transition,2,Energy Access,Energy lorem ipsum alo vil,25
25,Text,,5.3.2,Energy Transition,2,Energy Access,,26
26,Text,,5.3.2,Energy Transition,2,Energy Access,**Diagram**,27
27,Text,,5.3.2,Energy Transition,2,Energy Access,,28
28,Diagram,transition-2,5.3.2,Energy Transition,2,Energy Access,,29
29,Text,,5.3.2,Energy Transition,2,Energy Access,,30
30,Text,,5.3.2,Energy Transition,2,Energy Access,Here the diagram shows that renewable energy i...,31
31,Text,,5.3.2,Energy Transition,2,Energy Access,,32
32,Text,,5.3.2,Energy Transition,2,Energy Access,,33
33,Text,,5.3.2,Energy Transition,2,Energy Access,**Text-dark-6**,34
34,Text,,5.3.2,Energy Transition,2,Energy Access,,35
35,Text,,5.3.2,Energy Transition,2,Energy Access,<h3>Energy lorem ipsum alo vil cu li li oppo e...,36
36,Text,,5.3.2,Energy Transition,2,Energy Access,<h2>Energy lorem ipsum alo vil cu li li oppo e...,37
37,Text,,5.3.2,Energy Transition,2,Energy Access,<h4>Energy lorem ipsum alo vil cu li li oppo e...,38
38,Text,,5.3.2,Energy Transition,2,Energy Access,,39
39,Text,,5.3.2,Energy Transition,2,Energy Access,,40
40,Text,,5.3.2,Energy Transition,2,Energy Access,**Text-dark-4**,41
41,Text,,5.3.2,Energy Transition,2,Energy Access,<h4></h4>,42
42,Text,,5.3.2,Energy Transition,2,Energy Access,<h4>Energy lorem ipsum alo vil cu li li oppo e...,43
43,Text,,5.3.2,Energy Transition,2,Energy Access,,44
44,Text,,5.3.2,Energy Transition,2,Energy Access,,45
45,Text,,5.3.2,Energy Transition,2,Energy Access,**Photo-5**,46
46,Text,,5.3.2,Energy Transition,2,Energy Access,,47
47,Photo,access-1,5.3.2,Energy Transition,2,Energy Access,,48
48,Text,,5.3.2,Energy Transition,2,Energy Access,,49
49,Text,,5.3.2,Energy Transition,2,Energy Access,**Photo-6**,50
50,Text,,5.3.2,Energy Transition,2,Energy Access,,51
51,Photo,access-2,5.3.2,Energy Transition,2,Energy Access,,52
52,Text,,5.3.2,Energy Transition,2,Energy Access,,53
53,Text,,5.3.2,Energy Transition,2,Energy Access,,54
54,Text,,5.3.2,Energy Transition,2,Energy Access,*****,55

In [6]:
def extract_text_with_styles(doc):
    """Extracts text from a DOCX document, preserving some style elements, including text size."""
    text = []
    for para in doc.paragraphs:
        para_text = ""
        for run in para.runs:
            style_prefix = ""
            style_suffix = ""
            # Basic styles
            if run.bold:
                style_prefix += "<b>"
                style_suffix = "</b>" + style_suffix
            if run.italic:
                style_prefix += "<i>"
                style_suffix = "</i>" + style_suffix
            if run.underline:
                style_prefix += "<u>"
                style_suffix = "</u>" + style_suffix
            # Text color
            if run.font.color.rgb:
                color = run.font.color.rgb  # Color is an RGBColor object
                style_prefix += f'<span style="color:#{color}">'
                style_suffix = "</span>" + style_suffix
            # Text size
            if run.font.size:  # Font size is reported in Pt
                size_pt = run.font.size.pt
                if size_pt > 12:  # Assuming default text size is 12pt, customize as needed
                    style_prefix += f'<span style="font-size:{size_pt}pt;">'
                    style_suffix = "</span>" + style_suffix

            para_text += f"{style_prefix}{run.text}{style_suffix}"

        # Heading handling
        if para.style.name.startswith('Heading'):
            level = para.style.name.split()[-1]
            text.append(f'<h{level}>{para_text}</h{level}>')
        else:
            text.append(para_text)
    return '\n'.join(text)


# The updated function for parsing the document text
def parse_document(document_text):
    data = []
    section_num, section_title, slide_title = '', '', ''
    slide_number = 0

    lines = document_text.split('\n')
    for line in lines:
        section_header_match = re.match(r'#\s*(\d+\.\d+\.\d+)\s+(.*)', line)
        if section_header_match:
            section_num = section_header_match.group(1)
            section_title = section_header_match.group(2)
            slide_number = 0
            continue

        if '*Slide*' in line:
            slide_number += 1
            slide_title = re.findall(r'\[([^\]]+)\]', line)[0]
            continue

        if 'img=' in line or 'dgm=' in line:
            code_type, code = line.split('=')
            row_type = 'Photo' if 'img' in code_type else 'Diagram'
            data.append({
                'Type': row_type,
                'Code': code.strip(),
                'Section Number': section_num,
                'Section Title': section_title,
                'Slide Number': slide_number,
                'Slide Title': slide_title,
                'Text': '',
                'Column Number': '',
                'Column Width': '',
                'Theme': ''
            })
        else:
            match = re.match(r'(\*\*Text-([^\-]+)-?(\d*)\*\*)', line)
            text_type, width, theme = 'Text', '', ''
            column_number = ''
            if match:
                details = match.group(2).split('-')
                width = details[0]
                if len(details) > 1:
                    theme = details[1]
                column_number = match.group(3) if match.group(3) else '1'
            data.append({
                'Type': text_type,
                'Code': '',
                'Section Number': section_num,
                'Section Title': section_title,
                'Slide Number': slide_number,
                'Slide Title': slide_title,
                'Text': line,
                'Column Number': column_number,
                'Column Width': width,
                'Theme': theme
            })

    return pd.DataFrame(data)

# Reading the DOCX file
doc_path = '../03_Inputs/Modules/sea-test.docx'
doc = Document(doc_path)
document_text = extract_text_with_styles(doc)  # This function needs to be defined as well or imported if it's not in this snippet
df = parse_document(document_text)
df

,Type,Code,Section Number,Section Title,Slide Number,Slide Title,Text,Column Number,Column Width,Theme
0,Text,,5.3.2,Energy Transition,0,,,,,
1,Text,,5.3.2,Energy Transition,1,Innovation in the Just Energy Transition,,,,
2,Text,,5.3.2,Energy Transition,1,Innovation in the Just Energy Transition,,,,
3,Text,,5.3.2,Energy Transition,1,Innovation in the Just Energy Transition,**Photo**,,,
4,Text,,5.3.2,Energy Transition,1,Innovation in the Just Energy Transition,,,,
5,Photo,access-1,5.3.2,Energy Transition,1,Innovation in the Just Energy Transition,,,,
6,Text,,5.3.2,Energy Transition,1,Innovation in the Just Energy Transition,,,,
7,Text,,5.3.2,Energy Transition,1,Innovation in the Just Energy Transition,**Text-narrow**,1,narrow,
8,Text,,5.3.2,Energy Transition,1,Innovation in the Just Energy Transition,,,,
9,Text,,5.3.2,Energy Transition,1,Innovation in the Just Energy Transition,Energy lorem ipsum alo vil cu li li oppo energ...,,,
10,Text,,5.3.2,Energy Transition,1,Innovation in the Just Energy Transition,,,,
11,Text,,5.3.2,Energy Transition,1,Innovation in the Just Energy Transition,,,,
12,Text,,5.3.2,Energy Transition,1,Innovation in the Just Energy Transition,**Text-wide**,1,wide,
13,Text,,5.3.2,Energy Transition,1,Innovation in the Just Energy Transition,<h1>Energy lorem ipsum alo vil cu li li oppo <...,,,
14,Text,,5.3.2,Energy Transition,1,Innovation in the Just Energy Transition,Energy lorem <b>ipsum </b><b>alo</b><b> </b><b...,,,
15,Text,,5.3.2,Energy Transition,1,Innovation in the Just Energy Transition,Energy lorem ipsum alo vil cu li li oppo energ...,,,
16,Text,,5.3.2,Energy Transition,1,Innovation in the Just Energy Transition,,,,
17,Text,,5.3.2,Energy Transition,2,Energy Access,,,,
18,Text,,5.3.2,Energy Transition,2,Energy Access,**Photo-Box**,,,
19,Text,,5.3.2,Energy Transition,2,Energy Access,,,,
20,Photo,access-3,5.3.2,Energy Transition,2,Energy Access,,,,
21,Text,,5.3.2,Energy Transition,2,Energy Access,,,,
22,Text,,5.3.2,Energy Transition,2,Energy Access,**Text**,,,
23,Text,,5.3.2,Energy Transition,2,Energy Access,,,,
24,Text,,5.3.2,Energy Transition,2,Energy Access,Energy lorem ipsum alo vil,,,
25,Text,,5.3.2,Energy Transition,2,Energy Access,,,,
26,Text,,5.3.2,Energy Transition,2,Energy Access,**Diagram**,,,
27,Text,,5.3.2,Energy Transition,2,Energy Access,,,,
28,Diagram,transition-2,5.3.2,Energy Transition,2,Energy Access,,,,
29,Text,,5.3.2,Energy Transition,2,Energy Access,,,,
30,Text,,5.3.2,Energy Transition,2,Energy Access,Here the diagram shows that renewable energy i...,,,
31,Text,,5.3.2,Energy Transition,2,Energy Access,,,,
32,Text,,5.3.2,Energy Transition,2,Energy Access,,,,
33,Text,,5.3.2,Energy Transition,2,Energy Access,**Text-dark-6**,6,dark,
34,Text,,5.3.2,Energy Transition,2,Energy Access,,,,
35,Text,,5.3.2,Energy Transition,2,Energy Access,<h3>Energy lorem ipsum alo vil cu li li oppo e...,,,
36,Text,,5.3.2,Energy Transition,2,Energy Access,<h2>Energy lorem ipsum alo vil cu li li oppo e...,,,
37,Text,,5.3.2,Energy Transition,2,Energy Access,<h4>Energy lorem ipsum alo vil cu li li oppo e...,,,
38,Text,,5.3.2,Energy Transition,2,Energy Access,,,,
39,Text,,5.3.2,Energy Transition,2,Energy Access,,,,
40,Text,,5.3.2,Energy Transition,2,Energy Access,**Text-dark-4**,4,dark,
41,Text,,5.3.2,Energy Transition,2,Energy Access,<h4></h4>,,,
42,Text,,5.3.2,Energy Transition,2,Energy Access,<h4>Energy lorem ipsum alo vil cu li li oppo e...,,,
43,Text,,5.3.2,Energy Transition,2,Energy Access,,,,
44,Text,,5.3.2,Energy Transition,2,Energy Access,,,,
45,Text,,5.3.2,Energy Transition,2,Energy Access,**Photo-5**,,,
46,Text,,5.3.2,Energy Transition,2,Energy Access,,,,
47,Photo,access-1,5.3.2,Energy Transition,2,Energy Access,,,,
48,Text,,5.3.2,Energy Transition,2,Energy Access,,,,
49,Text,,5.3.2,Energy Transition,2,Energy Access,**Photo-6**,,,
50,Text,,5.3.2,Energy Transition,2,Energy Access,,,,
51,Photo,access-2,5.3.2,Energy Transition,2,Energy Access,,,,
52,Text,,5.3.2,Energy Transition,2,Energy Access,,,,
53,Text,,5.3.2,Energy Transition,2,Energy Access,,,,
54,Text,,5.3.2,Energy Transition,2,Energy Access,*****,,,

In [23]:
def extract_text_with_styles(doc):
    """Extracts text from a DOCX document, preserving some style elements, including text size."""
    text = []
    for para in doc.paragraphs:
        para_text = ""
        for run in para.runs:
            style_prefix = ""
            style_suffix = ""
            # Basic styles
            if run.bold:
                style_prefix += "<b>"
                style_suffix = "</b>" + style_suffix
            if run.italic:
                style_prefix += "<i>"
                style_suffix = "</i>" + style_suffix
            if run.underline:
                style_prefix += "<u>"
                style_suffix = "</u>" + style_suffix
            # Text color
            if run.font.color.rgb:
                color = run.font.color.rgb  # Color is an RGBColor object
                style_prefix += f'<span style="color:#{color}">'
                style_suffix = "</span>" + style_suffix
            # Text size
            if run.font.size:  # Font size is reported in Pt
                size_pt = run.font.size.pt
                if size_pt > 12:  # Assuming default text size is 12pt, customize as needed
                    style_prefix += f'<span style="font-size:{size_pt}pt;">'
                    style_suffix = "</span>" + style_suffix

            para_text += f"{style_prefix}{run.text}{style_suffix}"

        # Heading handling
        if para.style.name.startswith('Heading'):
            level = para.style.name.split()[-1]
            text.append(f'<h{level}>{para_text}</h{level}>')
        else:
            text.append(para_text)
    return '\n'.join(text)


def parse_document(document_text):
    # Initialize variables
    data = []
    section_num, section_title, slide_title = '', '', ''
    slide_number = 0  # Slide numbering starts at 0 and increments each time a new slide is found
    column_number = 0  # Initialize column number, which increments with each new section

    lines = document_text.split('\n')
    for line in lines:
        # Handle section headers
        section_header_match = re.match(r'#\s*(\d+\.\d+\.\d+)\s+(.*)', line)
        if section_header_match:
            section_num = section_header_match.group(1)
            section_title = section_header_match.group(2)
            slide_number = 0  # Reset slide number for each new section
            column_number += 1  # Increment column number for each new section
            continue  # Skip adding a row for the section header

        if '*Slide*' in line:
            # Increment slide number for each new slide
            slide_number += 1
            slide_title = re.findall(r'\[([^\]]+)\]', line)[0]
            continue  # Skip adding a row for the slide title

        width = ''  # Default empty string for width
        theme = ''  # Default empty string for theme

        if 'img=' in line or 'dgm=' in line or 'imgBox=' in line:
            code_type, code = line.split('=')
            if 'imgBox' in code_type:
                row_type = 'PhotoBox'
            elif 'img' in code_type:
                row_type = 'Photo'
            else:
                row_type = 'Diagram'
#             row_type = 'Photo' if 'img' in code_type else 'Diagram'
            data.append({
                'Type': row_type,
                'Code': code.strip(),
                'Section Number': section_num,
                'Section Title': section_title,
                'Slide Number': slide_number,
                'Slide Title': slide_title,
                'Text': '',
                'Column Number': column_number,  # Reflects the section as a new slide
                'Column Width': width,
                'Theme': theme
            })
        else:
            # Extract text type details for width and theme
            text_details = re.findall(r'\*\*Text-([^\*]+)\*\*', line)
            if text_details:
                details = text_details[0].split('-')
                if 'narrow' in details[0] or 'wide' in details[0]:
                    width = details[0]
                if 'dark' in details[0] or 'light' in details[0]:
                    theme = details[0]

            # Add regular text content
            data.append({
                'Type': 'Text',
                'Code': '',
                'Section Number': section_num,
                'Section Title': section_title,
                'Slide Number': slide_number,
                'Slide Title': slide_title,
                'Text': line,
                'Column Number': column_number,  # Reflects the section as a new slide
                'Column Width': width,
                'Theme': theme
            })

    return pd.DataFrame(data)


# Reading the DOCX file
doc_path = '../03_Inputs/Modules/sea-test.docx'
doc = Document(doc_path)
document_text = extract_text_with_styles(doc)  # This function needs to be defined as well or imported if it's not in this snippet
df = parse_document(document_text)
df

,Type,Code,Section Number,Section Title,Slide Number,Slide Title,Text,Column Number,Column Width,Theme
0,Text,,5.3.2,Energy Transition,0,,,1,,
1,Text,,5.3.2,Energy Transition,1,Innovation in the Just Energy Transition,,1,,
2,Text,,5.3.2,Energy Transition,1,Innovation in the Just Energy Transition,,1,,
3,Text,,5.3.2,Energy Transition,1,Innovation in the Just Energy Transition,**Photo**,1,,
4,Text,,5.3.2,Energy Transition,1,Innovation in the Just Energy Transition,,1,,
5,Photo,access-1,5.3.2,Energy Transition,1,Innovation in the Just Energy Transition,,1,,
6,Text,,5.3.2,Energy Transition,1,Innovation in the Just Energy Transition,,1,,
7,Text,,5.3.2,Energy Transition,1,Innovation in the Just Energy Transition,**Text-narrow**,1,narrow,
8,Text,,5.3.2,Energy Transition,1,Innovation in the Just Energy Transition,,1,,
9,Text,,5.3.2,Energy Transition,1,Innovation in the Just Energy Transition,Energy lorem ipsum alo vil cu li li oppo energ...,1,,
10,Text,,5.3.2,Energy Transition,1,Innovation in the Just Energy Transition,,1,,
11,Text,,5.3.2,Energy Transition,1,Innovation in the Just Energy Transition,,1,,
12,Text,,5.3.2,Energy Transition,1,Innovation in the Just Energy Transition,**Text-wide**,1,wide,
13,Text,,5.3.2,Energy Transition,1,Innovation in the Just Energy Transition,<h1>Energy lorem ipsum alo vil cu li li oppo <...,1,,
14,Text,,5.3.2,Energy Transition,1,Innovation in the Just Energy Transition,Energy lorem <b>ipsum </b><b>alo</b><b> </b><b...,1,,
15,Text,,5.3.2,Energy Transition,1,Innovation in the Just Energy Transition,Energy lorem ipsum alo vil cu li li oppo energ...,1,,
16,Text,,5.3.2,Energy Transition,1,Innovation in the Just Energy Transition,,1,,
17,Text,,5.3.2,Energy Transition,2,Energy Access,,1,,
18,Text,,5.3.2,Energy Transition,2,Energy Access,**Photo-Box**,1,,
19,Text,,5.3.2,Energy Transition,2,Energy Access,,1,,
20,PhotoBox,access-3,5.3.2,Energy Transition,2,Energy Access,,1,,
21,Text,,5.3.2,Energy Transition,2,Energy Access,,1,,
22,Text,,5.3.2,Energy Transition,2,Energy Access,**Text**,1,,
23,Text,,5.3.2,Energy Transition,2,Energy Access,,1,,
24,Text,,5.3.2,Energy Transition,2,Energy Access,Energy lorem ipsum alo vil,1,,
25,Text,,5.3.2,Energy Transition,2,Energy Access,,1,,
26,Text,,5.3.2,Energy Transition,2,Energy Access,**Diagram**,1,,
27,Text,,5.3.2,Energy Transition,2,Energy Access,,1,,
28,Diagram,transition-2,5.3.2,Energy Transition,2,Energy Access,,1,,
29,Text,,5.3.2,Energy Transition,2,Energy Access,,1,,
30,Text,,5.3.2,Energy Transition,2,Energy Access,Here the diagram shows that renewable energy i...,1,,
31,Text,,5.3.2,Energy Transition,2,Energy Access,,1,,
32,Text,,5.3.2,Energy Transition,2,Energy Access,,1,,
33,Text,,5.3.2,Energy Transition,2,Energy Access,**Text-dark-6**,1,,dark
34,Text,,5.3.2,Energy Transition,2,Energy Access,,1,,
35,Text,,5.3.2,Energy Transition,2,Energy Access,<h3>Energy lorem ipsum alo vil cu li li oppo e...,1,,
36,Text,,5.3.2,Energy Transition,2,Energy Access,<h2>Energy lorem ipsum alo vil cu li li oppo e...,1,,
37,Text,,5.3.2,Energy Transition,2,Energy Access,<h4>Energy lorem ipsum alo vil cu li li oppo e...,1,,
38,Text,,5.3.2,Energy Transition,2,Energy Access,,1,,
39,Text,,5.3.2,Energy Transition,2,Energy Access,,1,,
40,Text,,5.3.2,Energy Transition,2,Energy Access,**Text-dark-4**,1,,dark
41,Text,,5.3.2,Energy Transition,2,Energy Access,<h4></h4>,1,,
42,Text,,5.3.2,Energy Transition,2,Energy Access,<h4>Energy lorem ipsum alo vil cu li li oppo e...,1,,
43,Text,,5.3.2,Energy Transition,2,Energy Access,,1,,
44,Text,,5.3.2,Energy Transition,2,Energy Access,,1,,
45,Text,,5.3.2,Energy Transition,2,Energy Access,**Photo-5**,1,,
46,Text,,5.3.2,Energy Transition,2,Energy Access,,1,,
47,Photo,access-1,5.3.2,Energy Transition,2,Energy Access,,1,,
48,Text,,5.3.2,Energy Transition,2,Energy Access,,1,,
49,Text,,5.3.2,Energy Transition,2,Energy Access,**Photo-6**,1,,
50,Text,,5.3.2,Energy Transition,2,Energy Access,,1,,
51,Photo,access-2,5.3.2,Energy Transition,2,Energy Access,,1,,
52,Text,,5.3.2,Energy Transition,2,Energy Access,,1,,
53,Text,,5.3.2,Energy Transition,2,Energy Access,,1,,
54,Text,,5.3.2,Energy Transition,2,Energy Access,*****,1,,

### The results above record empty lines in between, below is when the empty lines are skipped.

In [21]:
def extract_text_with_styles(doc):
    """Extracts text from a DOCX document, preserving some style elements, including text size."""
    text = []
    for para in doc.paragraphs:
        para_text = ""
        for run in para.runs:
            style_prefix = ""
            style_suffix = ""
            # Basic styles
            if run.bold:
                style_prefix += "<b>"
                style_suffix = "</b>" + style_suffix
            if run.italic:
                style_prefix += "<i>"
                style_suffix = "</i>" + style_suffix
            if run.underline:
                style_prefix += "<u>"
                style_suffix = "</u>" + style_suffix
            # Text color
            if run.font.color.rgb:
                color = run.font.color.rgb  # Color is an RGBColor object
                style_prefix += f'<span style="color:#{color}">'
                style_suffix = "</span>" + style_suffix
            # Text size
            if run.font.size:  # Font size 
                size_pt = run.font.size.pt
                if size_pt > 12:  # Assuming default text size is 12pt, customize as needed
                    style_prefix += f'<span style="font-size:{size_pt}pt;">'
                    style_suffix = "</span>" + style_suffix

            para_text += f"{style_prefix}{run.text}{style_suffix}"

        # Heading handling
        if para.style.name.startswith('Heading'):
            level = para.style.name.split()[-1]
            text.append(f'<h{level}>{para_text}</h{level}>')
        else:
            text.append(para_text)
    return '\n'.join(text)


def parse_document(document_text):
    data = []
    section_num, section_title, slide_title = '', '', ''
    slide_number = 0  # Slide numbering starts at 0 and increments each time a new slide is found
    column_number = 0  # Initialize column number, which increments with each new section

    lines = document_text.split('\n')
    for line in lines:
        if not line.strip():  # Skip completely empty lines
            continue

        section_header_match = re.match(r'#\s*(\d+\.\d+\.\d+)\s+(.*)', line)
        if section_header_match:
            section_num = section_header_match.group(1)
            section_title = section_header_match.group(2)
            slide_number = 0  # Reset slide number for each new section
            column_number += 1  # Increment column number for each new section
            continue  # Skip adding a row for the section header

        if '*Slide*' in line:
            slide_number += 1
            slide_title = re.findall(r'\[([^\]]+)\]', line)[0]
            continue

        width = ''  # Default empty string for width
        theme = ''  # Default empty string for theme

        if 'img=' in line or 'dgm=' in line or 'imgBox=' in line:
            code_type, code = line.split('=')
            if 'imgBox' in code_type:
                row_type = 'PhotoBox'
            elif 'img' in code_type:
                row_type = 'Photo'
            else:
                row_type = 'Diagram'
#             row_type = 'Photo' if 'img' in code_type else 'Diagram'
            data.append({
                'Type': row_type,
                'Code': code.strip(),
                'Section Number': section_num,
                'Section Title': section_title,
                'Slide Number': slide_number,
                'Slide Title': slide_title,
                'Text': '',
                'Column Number': column_number,
                'Column Width': width,
                'Theme': theme
            })
        else:
            text_details = re.findall(r'\*\*Text-([^\*]+)\*\*', line)
            if text_details:
                details = text_details[0].split('-')
                if 'narrow' in details[0] or 'wide' in details[0]:
                    width = details[0]
                if 'dark' in details[0] or 'light' in details[0]:
                    theme = details[0]

            data.append({
                'Type': 'Text',
                'Code': '',
                'Section Number': section_num,
                'Section Title': section_title,
                'Slide Number': slide_number,
                'Slide Title': slide_title,
                'Text': line,
                'Column Number': column_number,
                'Column Width': width,
                'Theme': theme
            })

    return pd.DataFrame(data)



# Reading the DOCX file
doc_path = '../03_Inputs/Modules/sea-test.docx'
doc = Document(doc_path)
document_text = extract_text_with_styles(doc)  # This function needs to be defined as well or imported if it's not in this snippet
df = parse_document(document_text)
df

,Type,Code,Section Number,Section Title,Slide Number,Slide Title,Text,Column Number,Column Width,Theme
0,Text,,5.3.2,Energy Transition,1,Innovation in the Just Energy Transition,**Photo**,1,,
1,Photo,access-1,5.3.2,Energy Transition,1,Innovation in the Just Energy Transition,,1,,
2,Text,,5.3.2,Energy Transition,1,Innovation in the Just Energy Transition,**Text-narrow**,1,narrow,
3,Text,,5.3.2,Energy Transition,1,Innovation in the Just Energy Transition,Energy lorem ipsum alo vil cu li li oppo energ...,1,,
4,Text,,5.3.2,Energy Transition,1,Innovation in the Just Energy Transition,**Text-wide**,1,wide,
5,Text,,5.3.2,Energy Transition,1,Innovation in the Just Energy Transition,<h1>Energy lorem ipsum alo vil cu li li oppo <...,1,,
6,Text,,5.3.2,Energy Transition,1,Innovation in the Just Energy Transition,Energy lorem <b>ipsum </b><b>alo</b><b> </b><b...,1,,
7,Text,,5.3.2,Energy Transition,1,Innovation in the Just Energy Transition,Energy lorem ipsum alo vil cu li li oppo energ...,1,,
8,Text,,5.3.2,Energy Transition,2,Energy Access,**Photo-Box**,1,,
9,PhotoBox,access-3,5.3.2,Energy Transition,2,Energy Access,,1,,
10,Text,,5.3.2,Energy Transition,2,Energy Access,**Text**,1,,
11,Text,,5.3.2,Energy Transition,2,Energy Access,Energy lorem ipsum alo vil,1,,
12,Text,,5.3.2,Energy Transition,2,Energy Access,**Diagram**,1,,
13,Diagram,transition-2,5.3.2,Energy Transition,2,Energy Access,,1,,
14,Text,,5.3.2,Energy Transition,2,Energy Access,Here the diagram shows that renewable energy i...,1,,
15,Text,,5.3.2,Energy Transition,2,Energy Access,**Text-dark-6**,1,,dark
16,Text,,5.3.2,Energy Transition,2,Energy Access,<h3>Energy lorem ipsum alo vil cu li li oppo e...,1,,
17,Text,,5.3.2,Energy Transition,2,Energy Access,<h2>Energy lorem ipsum alo vil cu li li oppo e...,1,,
18,Text,,5.3.2,Energy Transition,2,Energy Access,<h4>Energy lorem ipsum alo vil cu li li oppo e...,1,,
19,Text,,5.3.2,Energy Transition,2,Energy Access,**Text-dark-4**,1,,dark
20,Text,,5.3.2,Energy Transition,2,Energy Access,<h4></h4>,1,,
21,Text,,5.3.2,Energy Transition,2,Energy Access,<h4>Energy lorem ipsum alo vil cu li li oppo e...,1,,
22,Text,,5.3.2,Energy Transition,2,Energy Access,**Photo-5**,1,,
23,Photo,access-1,5.3.2,Energy Transition,2,Energy Access,,1,,
24,Text,,5.3.2,Energy Transition,2,Energy Access,**Photo-6**,1,,
25,Photo,access-2,5.3.2,Energy Transition,2,Energy Access,,1,,
26,Text,,5.3.2,Energy Transition,2,Energy Access,*****,1,,

In [25]:
# Save in a outputs folder as a csv

output_dir = '../04_Outputs/Modules'
filename = 'parsed_data.csv'  
file_path = os.path.join(output_dir, filename)
df.to_csv(file_path, index=False)

## API Creation

In [27]:
from flask import Flask, jsonify, request
import pandas as pd

# Preparing the flask app
app = Flask(__name__)

# Load your data
df = pd.read_csv('../04_Outputs/Modules/parsed_data.csv')

@app.route('/')
def index():
    return "Welcome to the Academy Data Pipeline API!"

@app.route('/data', methods=['GET'])
def get_data():
    data = df.to_dict(orient='records')  # Convert DataFrame to a list of dictionaries
    return jsonify(data)

if __name__ == '__main__':
    app.run(debug=True)

 * Serving Flask app "__main__" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on

 * Restarting with watchdog (windowsapi)

SystemExit: 1

C:\Users\shima\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3377: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)